FROM node:14.13.1-alpine as builder

WORKDIR /app

COPY ./e2e-frontend/package*.json ./ 

RUN npm install
COPY ./e2e-frontend ./ 
RUN npm run build

FROM nginx:mainline 
RUN rm /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx/default.conf.template /etc/nginx/templates/