apiVersion: v1
kind: Service
metadata:
  labels:
    app: react-ui
  name: react-ui
spec:
  type: NodePort
  ports:
    - name: 3000-tcp
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: react-ui
